img/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :images do
    resources :tags, shallow: true
    resources :accessors, shallow: true
  end

  
  root 'images#index'

end

img/app/models/accessor.rb
class Accessor < ActiveRecord::Base
  belongs_to :image
  belongs_to :user

  validates :image_id, presence: true
  validates :user_id, presence: true 

end

img/app/models/image.rb
class Image < ActiveRecord::Base
  
  belongs_to :user
  has_many :tags, dependent: :destroy
  has_many :accessors, dependent: :destroy
  has_many :users, through: :accessors

  accepts_nested_attributes_for :tags
  accepts_nested_attributes_for :accessors


  def generate_filename
    rand(36**16).to_s(36) + ".jpg"
  end


end

img/app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :image
end

img/app/controllers/accessors_controller.rb
class AccessorsController < ApplicationController
  before_action :set_accessor, only: [:edit, :update, :destroy]

  def index
    @image = Image.find params[:image_id]
    @accessors = @image.accessors
  end

  def new
    @image = Image.find params[:image_id]
    @accessor = @image.accessors.new
  end

  def create
    @image = Image.find params[:image_id]
    @accessor = @image.accessors.new(accessor_params)

    if @accessor.save
      redirect_to image_url(@image) , notice: 'Accessor was successfully created.'
    else
      render :new
    end
  end

  def update
    if @accessor.update(accessor_params)
      redirect_to image_url(@accessor.image), notice: 'Accessor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @accessor.destroy
    redirect_to image_url(@accessor.image) , notice: 'Accessor was successfully destroyed.'
  end

  private
    def set_accessor
      @accessor = Accessor.find(params[:id])
    end

    def accessor_params
      params.require(:accessor).permit(:image_id, :user_id)
    end

end

img/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #before_filter :authenticate_user!

end

img/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
    @user = User.all
    @accessors = Accessor.all
  end
  
  def show
    @images = Image.all
    @users = User.all
    @accessors = Accessor.all
    @tag = @image.tags.new
    @accessor = @image.accessors.new
  end

  def new
    @image = Image.new
    @image.tags.new
    @image.accessors.new
  end

  def edit
  end

  def create
    # POST /images
    @image = Image.new(image_params)
    @image.filename = @image.generate_filename
    @image.user = current_user

    @uploaded_io = params[:image][:uploaded_file]

    File.open(Rails.root.join('public', 'images', @image.filename), 'wb') do |file|
        file.write(@uploaded_io.read)
    end

    if @image.save
      redirect_to root_path, notice: 'Image was successfully created.'
    else
      render :new
    end

  end

  def update
   if @image.update(image_params)
      redirect_to @image, notice: 'Image was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @image.destroy
    redirect_to images_url
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:filename, :flag, :user_id, tags_attributes: [:tag, :image_id], accessors_attributes: [:image_id, :user_id])
    end
end

img/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:edit, :update, :destroy]

  # GET /images/:image_id/tags
  def index
    @image = Image.find params[:image_id]
    @tags = @image.tags
  end

  # GET images/:image_id/tags/new
  def new
    @image = Image.find params[:image_id]
    @tag = @image.tags.new
  end

  # GET /tags/1/edit
  def edit
    # edit routes are not nested (we already know our image's foreign_key)
  end

  # POST images:/:image_id/tags
  def create
    @image = Image.find params[:image_id]
    @tag = @image.tags.new(tag_params)

    if @tag.save
      redirect_to image_url(@image) , notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to image_url(@tag.image), notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to image_url(@tag.image) , notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:tag, :image_id)
    end
end

img/app/helpers/images_helper.rb
module ImagesHelper
end

img/app/views/accessors/_form.html.erb
<%= form_for([@image, @accessor]) do |f| %>
  <% if @accessor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accessor.errors.count, "error") %> prohibited this access from being saved:</h2>

      <ul>
      <% @accessor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<div class="field", class="actions">
  User_ID: <%= f.text_field :user_id %>
  <%= f.submit "New Accessor" %>
</div>


<% end %>

img/app/views/accessors/edit.html.erb
<h1>Edit accessor for <%= @accessor.image.filename %> </h1>

<%= render 'form' %>

<%= link_to 'Back', image_accessors_path(@accessor.image) %>

img/app/views/accessors/index.html.erb
<h1><%= @image.filename %>'s Accessors </h1>

<table>
  <thead>
    <tr>
      <th>User_ID</th>
      <th>Image_ID</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessors.each do |accessor| %>
      <tr>
        <td><%= accessor.user_id %></td>
        <td><%= accessor.image_id %></td>
        <td><%= link_to 'Edit', edit_accessor_path(accessor) %></td>
        <td><%= link_to 'Destroy', accessor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessor', new_image_accessor_path %> |
<%= link_to "Back", @image %>

img/app/views/accessors/new.html.erb
<h1>New accessor for <%= @image.filename %> </h1>

<%= render 'form' %>

<%= link_to 'Back', image_accessors_path %>

img/app/views/layouts/application.html.erb
<!DOCTYPE html>

<!--
<style>
div {
background-color: white;
width: 666px;
padding: 25px;
border: 25px solid navy;
margin: 25px;
}
</style>
<style>
body {
background-image: url("http://i.imgur.com/kLrAW0x.jpg");
background-color: #cccccc;
}
</style>
-->




<html>
<head>
  <title>Img</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<div id ="body">
<font color="blue">
<% if user_signed_in? %>
Signed in as <%= current_user.email %>. Not you?
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign Up", new_user_registration_path %> or
<%= link_to "Sign In", new_user_session_path %>
<% end %>
</font>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</div>
</html>