final/music/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index]
  resources :songs do
    resources :ratings, shallow: true
    resources :accessors, shallow: true
  end

  root 'songs#index'

  get 'songs/:id/downloadart', to: 'songs#downloadart', as: 'downloadart'
  get 'songs/:id/download', to: 'songs#download', as: 'download'

end

final/music/app/models/accessor.rb
class Accessor < ActiveRecord::Base

  belongs_to :user
  belongs_to :song

end

final/music/app/models/rating.rb
class Rating < ActiveRecord::Base

  validates :comment, presence: true
  validates :rating, presence: true

  belongs_to :song

end

final/music/app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  has_many :ratings, dependent: :destroy
  has_many :accessors, dependent: :destroy

  validates :artwork, presence: true
  validates :filename, presence: true
  validates :flag, presence: true
  validates :name, presence: true
  validates :artist, presence: true 
  validates :album, presence: true
  validates :genre, presence: true



  def generate_artwork_filename
    rand(36**16).to_s(36) + ".jpg"
  end


  def generate_song_filename
    rand(36**16).to_s(36)  + ".mp3"
  end


  def download_art
    Rails.root.join('public', 'images', self.artwork)
  end

  def download_song
    Rails.root.join('public', 'audios', self.filename)
  end

end

final/music/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable




  

end

final/music/app/controllers/accessors_controller.rb
class AccessorsController < ApplicationController
  before_action :set_accessor, only: [:edit, :update, :destroy]

  def index
    @song = Song.find params[:song_id]
    @users = User.all
     
    @accessors = @song.accessors
    #@accessor = @song.accessors.new
  end


  def edit
  end

  def new
    @song = Song.find params[:song_id]
    @users = User.all
    @accessor = @song.accessors.new
  end

  def create
    @song = Song.find params[:song_id]
    @accessor = @song.accessors.new(accessor_params)

    if @accessor.save
      redirect_to song_accessors_url(@song) , notice: 'Accessor was successfully created.'
    else
      render :new
    end
  end

  def update
    if @accessor.update(accessor_params)
      redirect_to song_accessors_url(@accessor.song), notice: 'Accessor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @accessor.destroy
    redirect_to song_accessors_url(@accessor.song), notice: 'Accessor was successfully destroyed.'
  end


  private
    def set_accessor
      @accessor = Accessor.find(params[:id])
    end

    def accessor_params
      params.require(:accessor).permit(:user_id, :song_id)
    end

end

final/music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception





  before_action :configure_permitted_parameters, if: :devise_controller?

      protected
          def configure_permitted_parameters
              devise_parameter_sanitizer.for(:sign_up) << :name
              devise_parameter_sanitizer.for(:account_update) << :name
          end



end

final/music/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    send_file(Rails.root.join('public', 'audios', @song.filename))
    #send_file(Rails.root.join('public', 'images', @song.artwork))
  end

end

final/music/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  before_action :set_rating, only: [:edit, :update, :destroy]

  def index
    @song = Song.find params[:song_id]
    @ratings = @song.ratings
  end

  def new
    @song = Song.find params[:song_id]
    @rating = @song.ratings.new
  end

  def edit
  end

  def create
    @song = Song.find params[:song_id]
    @rating = @song.ratings.new(rating_params)
    @rating.user_id = current_user.id

    if @rating.save
      redirect_to song_url(@song), notice: 'Rating was successfully created.'
    else
      render :new
    end
  end

  def update
    if @rating.update(rating_params)
      redirect_to song_url(@rating.song), notice: 'Rating was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @rating.destroy
    redirect_to song_url(@rating.song) , notice: 'Rating was successfully destroyed.'
  end

  private
    def set_rating
      @rating = Rating.find(params[:id])
    end

    def rating_params
      params.require(:rating).permit(:comment, :rating)
    end

end

final/music/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy, :downloadart, :download]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
    @accessors = Accessor.all
  end
  
  # GET /songs/1
  # GET /songs/1.json
  def show
    @songs = Song.all
    @users = User.all

    @user = @song.user
    @rating = @song.ratings.new

    #@download_song = send_file(@song.download_song)
    #@download_art = send_file(@song.download_art)
  end



  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    @song.artwork = @song.generate_artwork_filename
    @song.filename = @song.generate_song_filename
    @song.user = current_user

    @uploaded_io = params[:song][:uploaded_file]
    @uploaded_io2 = params[:song][:uploaded_file2]


    File.open(Rails.root.join('public', 'images', @song.artwork), 'wb') do |file|
      file.write(@uploaded_io.read)
    end

    File.open(Rails.root.join('public', 'audios', @song.filename), 'wb') do |file|
      file.write(@uploaded_io2.read)
    end

    if @song.save
      redirect_to @song, notice: 'Song was successfully created.'
    else
      render :new
    end
 
    @song.ratings.each do |new_rating|
      new_rating.user_id = current_user.id
    end



  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # GET /songs/1/downloadart
  def downloadart
    send_file(Rails.root.join('public', 'images', @song.artwork))
  end

  # GET /songs/1/download
  def download
    send_file(Rails.root.join('public', 'audios', @song.filename))
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:artwork, :filename, :flag, :name, :artist, :album, :genre, ratings_attributes: [:comment, :rating], accessors_attributes: [:user_id, :song_id])
    end
end

final/music/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end


  def show
    send_file(Rails.root.join('public', 'audios', @song.filename))
    send_file(Rails.root.join('public', 'images', @song.artwork))
  end 

  def edit   
  end


end

final/music/app/helpers/application_helper.rb
module ApplicationHelper
end

final/music/app/helpers/songs_helper.rb
module SongsHelper
end

final/music/app/views/ratings/_form.html.erb
<%= form_for([@song, @rating]) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.select :rating, options_for_select(["1", "2", "3", "4", "5"]) %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, :cols => "50", :rows => "7" %>
  </div>
  <div class="actions">
    <%= f.submit "Post" %>
  </div>
<% end %>

final/music/app/views/ratings/edit.html.erb
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  background-color: whitesmoke;
  padding: 5px;
  text-align: center;
}
th {
  background-color: navy;
}
td {
  background-color: whitesmoke;
}
#body {
background-attachment: fixed;
background-color: #cccccc;
background-image: url("http://i.imgur.com/kLrAW0x.jpg");
height: 100%;
}
</style>


<br>
<table width="45%" align="center">
<tr><th><h3><font color="white">Editing Rating for <%= @rating.song.name %></font></h3></th></tr>
<td>
  <br>
  <%= render 'form' %>
  <br>
  <%= link_to 'Back to Song', @rating.song %> | <%= link_to "All Songs", songs_path %>
</td>
</table>
<br>

final/music/app/views/ratings/index.html.erb
<h1><%= @song.name %>'s Ratings </h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.comment %></td>
        <td><%= rating.rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_song_rating_path %> |
<%= link_to "Back to #{@Song.name}'s page", song_path(@song) %>

final/music/app/views/ratings/new.html.erb
<h1> New Rating for <%= @song.name %></h1>

<%= render 'form' %>

<%= link_to Back, song_ratings_path(@song.name) %>

final/music/app/views/songs/edit.html.erb
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  background-color: whitesmoke;
  padding: 5px;
  text-align: center;
}
th {
  background-color: navy;
}
td {
  background-color: whitesmoke;
}
</style>


<br>
<table align="center">
<tr><th><h3><font color="white">Editing Song: <%= @song.name %></font></h3></th></tr>
<td>
  <br>
  <%= render 'form' %>
  <br>
  <%= link_to 'Back to Song', @song %> | <%= link_to "All Songs", songs_path %>
</td>
</table>
<br>

final/music/app/views/songs/index.html.erb
<!-- INDEX PAGE -->
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    background-color: whitesmoke;
    padding: 5px;
    text-align: center;
}
th {
  background-color: navy;
}
td {
  background-color: whitesmoke;
}
table#t01 th	{
    background-color: black;
    color: white;
}
</style>



<% if current_user == nil %>
<br>
  <table><tr><td><font color="blue"><b>  * </b></font><a href="http://ec2-54-68-223-204.us-west-2.compute.amazonaws.com/">AWS Home Page</a></td></tr></table>

<br>
<br>
  <table id="t01" align="center"><tr><th><h1>Music Marauder</h1></th></tr><table>
<br>
  <table align="center">
    <thead>
      <tr><th colspan="5" style="font-size:110%"><font style="color: white">10 Most Recent Uploads</font></th></tr> 
      <tr>
        <td><b>Title</b></td>
        <td><b>Artist</b></td>
        <td><b>Album</b></td>
        <td><b>Genre</b></td>
        <td><b>Upload Date</b></td>
      </tr>
    </thead>

    <tbody>
      <% for i in 0..9 %>
        <tr>
          <% if @songs[@songs.length-1-i].flag == "0" %>
            <td><%= image_tag @songs[@songs.length-1-i].artwork, size: "10x10", alt: @songs[@songs.length-1-i].artwork %> <%= link_to "#{@songs[@songs.length-1-i].name}", @songs[@songs.length-1-i] %></td>          
          <% else %>
            <td><%= image_tag @songs[@songs.length-1-i].artwork, size: "10x10", alt: @songs[@songs.length-1-i].artwork %> <%= @songs[@songs.length-1-i].name %></td>
          <% end %>
          <td><%= @songs[@songs.length-1-i].artist %></td>
          <td><%= @songs[@songs.length-1-i].album %></td>
          <td><%= @songs[@songs.length-1-i].genre %></td>
          <td><%= @songs[@songs.length-1-i].created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>
<br>

  <table align="center">
    <thead>
    <tr><th colspan="4" style="font-size:110%"><font style="color:white">Public Songs</font></th></tr>
    <tr>
       <td><b>Title</b></td>
       <td><b>Artist</b></td>
       <td><b>Album</b></td>
       <td><b>Genre</b></td>
    </tr>
    </thead>

    <tbody>
      <% @songs.each do |song| %>
      <% if song.flag == '0' %>
        <tr>
          <td><%= image_tag song.artwork, size: "10x10", alt: song.artwork %> <%= link_to "#{song.name}", song %></td>
          <td><%= song.artist %></td>
          <td><%= song.album %></td>
          <td><%= song.genre %></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
  <br>
  <br>




<!-- ###################################################################### -->




<% else %>

  <!-- CHECK FOR SPECIAL ACCESS -->
  <% special_access = 0 %>
  
  <% @songs.each do |song| %>
  <% song.accessors.each do |accessor| %>
    <% if accessor.user_id == current_user.id %>
      <% special_access = 1 %>
      <% break %>
    <% end %>
  <% end %>
  <% end %>
<br>
  <table>
    <tr><td><font color="blue"><b>  * </b></font><a href="http://ec2-54-68-223-204.us-west-2.compute.amazonaws.com/">AWS Home Page</a></td></tr>
  <tr><td><font color="blue"><b>  * </b></font><a href="http://ec2-54-68-223-204.us-west-2.compute.amazonaws.com/music/users/edit">Edit Account</a></td></tr><tr><td><font color="green"><b> + </b></font><%= link_to 'New Song', new_song_path %></td></tr></table>
<br>
<br>
  <table id="t01" align="center"><tr><th><h1>Music Marauder</h1></th></tr><table>
  <br>
  <table align="center">
    <thead>
      <tr><th colspan="5" style="font-size:110%"><font style="color:white">10 Most Recent Uploads</font></th></tr>
      <tr>
        <td><b>Title</b></td>
        <td><b>Artist</b></td>
        <td><b>Album</b></td>
        <td><b>Genre</b></td>
        <td><b>Upload Date</b></td>
      </tr>
    </thead>

    <tbody>
      <% for i in 0..9 %> 
        <tr>
          <% if @songs[@songs.length-1-i].flag == "0" || @songs[@songs.length-1-i].user_id == current_user.id || special_access == 1 %>
            <td><%= image_tag @songs[@songs.length-1-i].artwork, size: "10x10", alt: @songs[@songs.length-1-i].artwork %> <%= link_to "#{@songs[@songs.length-1-i].name}", @songs[@songs.length-1-i] %></td>
          <% else %>
            <td><%= image_tag @songs[@songs.length-1-i].artwork, size: "10x10", alt: @songs[@songs.length-1-i].artwork %> <%= @songs[@songs.length-1-i].name %></td>
          <% end %>

          <td><%= @songs[@songs.length-1-i].artist %></td>
          <td><%= @songs[@songs.length-1-i].album %></td>
          <td><%= @songs[@songs.length-1-i].genre %></td>
          <td><%= @songs[@songs.length-1-i].created_at %></td>
          </tr>

      <% end %>
    </tbody>
  </table>

<br>
<br>

  <table align="center">
    <thead>
      <tr><th colspan="5" style="font-size:110%"><font style="color:white">My Songs</font></th></tr>
      <tr>
        <td><b>Title</b></td>
        <td><b>Artist</b></td>
        <td><b>Album</b></td>
        <td><b>Genre</b></td>
      </tr>
    </thead>

    <tbody>
      <% @songs.each do |song| %>
      <% if song.user_id == current_user.id %>
        <tr>
          <td><%= image_tag song.artwork, size: "10x10", alt: song.artwork %> <%= link_to "#{song.name}", song %></td>
          <td><%= song.artist %></td>
          <td><%= song.album %></td>
          <td><%= song.genre %></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>

<br>
<br>

  <table align="center">
      <tr><th colspan=4><h3><font color="white">Accessible Songs</font></h3></th></tr>
      <tr>
         <td><b>Title</b></td>
         <td><b>Artist</b></td>
         <td><b>Album</b></td>
         <td><b>Genre</b></td>
      </tr>
      <% @songs.each do |song| %>
      <% song.accessors.each do |accessor| %>
        <tr>
        <% if accessor.user_id == current_user.id %>
          <td><%= image_tag song.artwork, size: "10x10", alt: song.artwork %> <%= link_to "#{song.name}", song %></td>
          <td><%= song.artist %></td>
          <td><%= song.album %></td>
          <td><%= song.genre %></td>
        <% end %>
        </tr>
      <% end %>
      <% end %>
      </tr>
  </table>

<br>
<br>

  <table align="center">
    <thead>
      <tr><th colspan="4" style="font-size:110%"><font style="color:white">Public Songs</font></th></tr>
      <tr>
        <td><b>Title</b></td>
        <td><b>Artist</b></td>
        <td><b>Album</b></td>
        <td><b>Genre</b></td>
      </tr>
    </thead>

    <tbody>
      <% @songs.each do |song| %>
        <% if song.flag == '0' %>
          <tr>
            <td><%= image_tag song.artwork, size: "10x10", alt: song.artwork %> <%= link_to "#{song.name}", song %></td>
            <td><%= song.artist %></td>
            <td><%= song.album %></td>
            <td><%= song.genre %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<br>
<br>



<% end %>

final/music/app/views/songs/new.html.erb
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  background-color: whitesmoke;
  padding: 5px;
  text-align: center;
}
th { 
  background-color: navy;
}
td {
  background-color: whitesmoke;
}
</style>



<br>
<table align="center">
<tr><th><h1><font color="white">New Song</font></h1></th></tr>
<td>
  <br>
  <%= render 'form' %>
  <br>
  <%= link_to 'All Songs', songs_path %>
</td>
</table>
<br>

final/music/app/views/songs/show.html.erb
<!-- SHOW PAGE -->
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  background-color: whitesmoke;
  padding: 5px;
  text-align: center;
}
th {
  background-color: navy;
}
td {
  background-color: whitesmoke;
}
</style>



<% if !current_user %> <!-- NO ONE LOGGED IN -->


  <% if @song.flag == "1" %><!-- PROTECT PRIVATE IMAGES -->
    <br>
    <table align="center" width="45%"><tr><td><br><br><b>You do not gave permission to view this page.</b><br><br><br></td></tr>
    <br>
    <tr>
    <td>
      <% if @song.name != @songs[0].name %>
        <%= link_to 'Previous Song', @songs[@song.id-2] %> |
      <% else %>
        First Song |
      <% end %>

      <%= link_to 'All Songs', songs_path %>

      <% if @song.name != @songs[@songs.length-1].name %>
        | <%= link_to 'Next Song', @songs[@song.id] %>
      <% else %>
        | Last Song
      <% end %>
    </td>
    </tr>
    <br>
    <br>
    <tr><td><a href="http://ec2-54-68-223-204.us-west-2.compute.amazonaws.com/">AWS Home Page</a></td></tr></table>




  <% else %><!-- NORMAL PUBLIC VIEW -->
    <table align="center"><tr><th><h2><font color="white"><%= @song.name %></font></h2></th></tr>
    <td>
    <%= image_tag root_url + "/images/" + @song.artwork, size: "400x400", alt: @song.artwork %>
    <br>
    <%= audio_tag("#{@song.filename}", autoplay: true, controls: true) %>

    <br>
    <font color='blue'>Owner: </font><%= @users[@song.user_id-1].name %> 
    <br>
    <% if @song.flag == '0' %>
      <font color="green">Public</font>
    <% elsif @song.flag == '1' %>
      <font color="red">Private</font>
    <% end %>
    <br>

    <p>
      <font color="green"><%= link_to "Download MP3", download_path %></font>

    </p>

    <p>
      <font color="green"><%= link_to "Download Artwork", downloadart_path %></font>
    </p>

    <p> 
      <strong>Song:</strong> 
      <%= @song.name %>
    </p>
    
    <p>
      <strong>Artist:</strong>
      <%= @song.artist %>
    </p>

    <p>
      <strong>Album:</strong>
      <%= @song.album %>
    </p>

    <p>
      <strong>Genre:</strong>
      <%= @song.genre %>
    </p>

    <% if @song.name != @songs[0].name %>
      <%= link_to 'Previous Song', @songs[@song.id-2] %> |
    <% else %>
      First Song |
    <% end %>

    <%= link_to 'All Songs', songs_path %> 

    <% if @song.name != @songs[@songs.length-1].name %>
      | <%= link_to 'Next Song', @songs[@song.id] %><br>
    <% else %>
      | Last Song <br>
    <% end %>
    <a href="http://ec2-54-68-223-204.us-west-2.compute.amazonaws.com/">AWS Home Page</a>
    </td>
    
    </table>
    <br>
    <br>
    <table align="center">
      <thead>
        <tr>
          <th><font color="white">User</font></th>
          <th><font color="white">Comment</font></th>
          <th><font color="white">Rating</font></th>
          <th> </th>
        </tr>
      </thead>

      <tbody>
        <% @song.ratings.reverse_each do |rating| %>
          <% if !rating.new_record? %>
          <tr>
            <td><%= @users[rating.user_id-1].name %></td>  
            <td><%= rating.comment %></td>
            <td><%= rating.rating %></td>
            <td><%= rating.updated_at %></td>
          <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>






<% else %> <!-- LOGGED IN -->
   
  <% special_access = 0 %>
  <% @song.accessors.each do |accessor| %>
    <% if accessor.user_id == current_user.id %>
      <% special_access = 1 %>
      <% break %>
    <% end %>
  <% end %> 

  <% if @song.flag == '1' && current_user.id != @song.user_id && special_access == 0 %>
    <br> 
    <table align="center" width="45%"><tr><td><br><br><b>You do not gave permission to view this page.</b><br><br><br></td></tr>
    <br>
    <tr>
    <td>
      <% if @song.name != @songs[0].name %>
        <%= link_to 'Previous Song', @songs[@song.id-2] %> |
      <% else %>
        First Song |
      <% end %>

      <%= link_to 'All Songs', songs_path %>

      <% if @song.name != @songs[@songs.length-1].name %>
        | <%= link_to 'Next Song', @songs[@song.id] %>
      <% else %>
        | Last Song
      <% end %>
    </td>
    </tr>
    <br>
    <br>
    <tr><td><a href="http://ec2-54-68-223-204.us-west-2.compute.amazonaws.com/">AWS Home Page</a></td></tr></table>


  <% else %>
  <!-- normal logged in view --> 
    <table align="center"><tr><th><h2><font color="white"><%= @song.name %></font></h2></th></tr>
    <td>

      <%= image_tag root_url + "/images/" + @song.artwork, size: "400x400", alt: @song.artwork %>
      <br>
      <%= audio_tag("#{@song.filename}", autoplay: true, controls: true) %>
      <br>


      <% if @song.user_id == current_user.id %>
        <font color='blue'>Owner: </font> You | <font color="blue">Options: </font>
        <%= link_to 'Edit', edit_song_path(@song) %>
        <%= link_to 'Destroy', @song, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% else %>
        <font color='blue'>Owner: </font><%= @users[@song.user_id-1].name %>
      <% end %>
      <br>

  
      <% if @song.flag == '0' %>
        <font color="green">Public</font>
      <% elsif @song.flag == '1' %>
        <font color="red">Private</font>
      <% end %>

      <% if @song.user_id == current_user.id && @song.flag =='1' %>
        | <%= link_to "Special Access", song_accessors_path(@song) %>
      <% elsif special_access == 1 %>
        | <font color="green">Special Access Granted</font>
      <% end %>

      

      <br>


      <p>
        <font color="green"><%= link_to "Download MP3", download_path %></font>
      </p>

      <p>
        <font color="green"><%= link_to "Download Artwork", downloadart_path %></font> 
      </p>

      <p>
        <strong>Song:</strong>
        <%= @song.name %>
      </p>

      <p>
        <strong>Artist:</strong>
        <%= @song.artist %>
      </p>

      <p>
        <strong>Album:</strong>
        <%= @song.album %>
      </p>

      <p>
        <strong>Genre:</strong>
        <%= @song.genre %>
      </p>


     <% if @song.name != @songs[0].name %>
       <%= link_to 'Previous Song', @songs[@song.id-2] %> | 
     <% else %>
       First Song |
     <% end %>

     <%= link_to 'All Songs', songs_path %> 

     <% if @song.name != @songs[@songs.length-1].name %>
       | <%= link_to 'Next Song', @songs[@song.id] %><br>
     <% else %>
       | Last Song <br>
     <% end %>  

     <a href="http://ec2-54-68-223-204.us-west-2.compute.amazonaws.com/">AWS Home Page</a>

    </td>
    </table>
    <br>
  
    <table width="35%" align="center"><tr><td><%= render 'ratings/form' %></td></tr></table>

    <br>
    <table align="center">
      <thead>
        <tr>
          <th><font color="white">User</font></th>
          <th><font color="white">Comment</font></th>
          <th><font color="white">Rating</font></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @song.ratings.reverse_each do |rating| %>
          <% if !rating.new_record? %>
          <tr>
            <td><%= @users[rating.user_id-1].name %></td>
            <td><%= rating.comment %></td>
            <td><%= rating.rating %></td>
            <td><%= rating.updated_at %></td>
            <% if rating.user_id == current_user.id %>
              <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
              <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
              <td colspan=2> </td>
            <% end %>    
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

  <% end %>

<% end %>

final/music/app/views/users/index.html.erb
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  background-color: whitesmoke;
  padding: 5px;
  text-align: center;
}
th {
  background-color: navy;
}
td {
  background-color: whitesmoke;
}
</style>

<table align="center" width="25%"><tr><th><h3><font color="white">Listing Users</font></h3></th></tr>
<tr><td>
<ul>
  <% @users.each do |user| %>
    <li><%= user.name %> | Registered On: <%= user.created_at %></li>
  <% end %>
</ul>
<%= link_to 'Back to Songs', songs_path %>
</td></tr></table>